name: ransomwatch

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

# to consider: the use of action jobs to breakout each task
# https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs

jobs:
  torsocks-job:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    services:
      torproxy:
        image: ghcr.io/joshhighet/torsocc@sha256:6b29e34bfe7e93ccad870f232537910f5e181e3cbb656575daf59ea74d5d96fd # TODO: Fork repo, review code, run under my account
        ports:
        - 9050:9050
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: run scraper
        run: |
          python3 ransomwatch.py scrape
      - name: run parser
        run: |
          python3 ransomwatch.py parse
      - name: generate markdown & graphs for docsify
        run: |
          python3 ransomwatch.py markdown
      - name: generate kv groups for analytics
        run: |
          python3 assets/groups-kv.py
      - name: save changes
        run: |  
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit --all --message "ğšŒğš›ğš˜ğš—ğš‹ğš˜ğš" || echo "no changes to commit"
          git push
